[MODEL] Added "default per page" methods for pagination with multi model searches
Due to the fact that different models aggregated on a multimodel search could have different default values for the page size. I have opted for defaulting to Kaminari's and WillPaginate's respective default values.

Problem:

    Elasticsearch::Model.search(query, [AAA, BBB]).page(1).results
    NoMethodError:
    undefined method `default_per_page' for #Elasticsearch::Model::Multimodel:0x007ff9dbe4f520

Fixes  #382
Closes #408